export default {
    admob_env: "live",
    admob_id: "ca-app-pub-7988641760569604/5696367049",
    admob_banner: "ca-app-pub-7988641760569604/8459968045",
    THEME:{
        blue_dark:{
            menu_button_color: ['#9dc8db', '#fff'],
            period_text: "#2CA5FC",
            cycle_text: "#76b0c9",
            submenu_button_color: ['#1156E9', '#2CA5FC', '#80EEFD'],
            icon_color: '#76b0c9',
            calendar_back: "#9dc8db",
            submenu_text1:"#fff",
            submenu_text2:"#d8d6d6",
            menu_text: "#5b5959"
        },
        orange_dark:{
            menu_button_color: ['#efc864', '#f2dca4'],
            period_text: "#DE602E",
            cycle_text: "#efc864",
            submenu_button_color: ['#D16716', '#E79658', '#EEB285'],
            icon_color: '#efc864',
            calendar_back: "#f2dca4",
            submenu_text1:"#fff",
            submenu_text2:"#d8d6d6",
            menu_text: "#5b5959"
        },
    },
    Labels:{
        en:{
            tab_calendar: "Calendar",
            tab_log: "Log",
            tab_chart: "Chart",
            tab_setting: "Setting",
            tab_note: "Add Note",
            period_text1: "st DAYS OF PERIOD",
            period_text2: "nd DAYS OF PERIOD",
            period_text3: "rd DAYS OF PERIOD",
            period_text4: "th DAYS OF PERIOD",
            cycle_text: "Days left",
            next_period: "Next period",
            next_text: "Next fertile",
            sub_theme: "Theme",
            sub_theme_text: "You can change the theme style & color",
            sub_symptomood: "Symptoms and Moods",
            sub_symptomood_text: "You can update the mood swings",
            sub_lang: "Language Options",
            sub_lang_text: "You can change the language",
            sub_metric: "Metric and Imperial units",
            sub_metric_text: "You can change your unit details",
            sub_reminder: "Reminder",
            sub_reminder_text: "Period, Ovulation and medicine reminder",
            sub_pass: "Password",
            sub_pass_text: "Secure your app authentication",
            sub_backup: "Backup & Restore",
            sub_backup_text: "Secure your data and get back anytime",
            dash_daysbaby: " days to baby",
            dash_preg:" since pregnancy",
            dash_title_details: "Enter your details",
            dash_length_of:"The length of your",
            dash_period_t:"Period",
            dash_bleed_bet: "Bleeding usually lasts between 4-7 days",
            dash_cannot_empty: "This field can not be empty",
            dash_length_mens: "The length of your menstrual cycle?",
            dash_duration_of:"The duration of two periods start date, usually 23-35 days.",
            dash_start_period: "The start date of your last period?",
            dash_date_valid: "Select the date first",
            dash_btn_cancel: "Cancel",
            dash_btn_done: "Done",
            dash_select_lang: "Select your language",
            dash_welcome: "Welcome",
            dash_new_user: "New user",
            dash_used_before: "I've used before",
            dash_restore: "Restore data",
            note_add_text: "Add Note",
            note_add_btn: "Add",
            note_condom: "Condom Option",
            note_unprotect: "Unprotected",
            note_protect: "Protected",
            note_orgasm: "Female Orgasm",
            note_yes: "Yes",
            note_no: "No",
            note_how_many: "How many times",
            note_weight: "Weight",
            note_height: "Height",
            note_temp: "Temperature",
            note_target: "Target",
            note_p_start: "Period Starts",
            note_flow: "Flow",
            note_p_end: "Period Ends",
            note_text: "Note",
            note_interc: "Intercourse",
            note_water: "Drink Water",
            user_add: "Add a new account",
            user_cancel: "CANCEL",
            user_add_text: "ADD",
            user_edit: "Edit",
            user_update_btn: "UPDATE",
            user_delete: "Delete",
            user_tap: "Tap to switch, lomg press to edit or delete",
            back_sync: "Sync Data",
            back_last_sync: "Last sync time ",
            back_signin: "Sign in and synchronize your data",
            back_lost_msg: "So your data won't be lost when your device changed.",
            back_signout: "Signout",
            bar_today: "Today",
            bar_ovul: "Ovulation",
            bar_add_p: "Add Period",
            bar_past: "Past",
            bar_pred: "Prediction",
            fertile_start: "Start",
            fertile_end: "End",
            ovu_luteal: "Luteal Phase Length",
            ovu_days: "Days",
            ovu_we_use: "We use this luteal phase length to predict your next ovulation.",
            ovu_update:"Update",
            set_period: "PERIOD",
            set_period_l: "Period Length",
            set_cycle_l: "Cycle Length",
            set_ovu: "Ovulation and Fertile",
            set_preg: "Pregnancy",
            set_remind_head: "REMINDERS",
            set_remind: "Reminders",
            set_remind_text: "Period, Ovulation and Medicine",
            set_person: "PERSONALIZE",
            set_theme: "Theme",
            set_cal: "Calendar",
            set_data: "DATA & ACCOUNT",
            set_add_another: "Add another user",
            set_gen: "GENERAL SETTING",
            set_other: "OTHERS",
            set_delete: "Delete all data",
            cycle_predict: "We use this cycle length to predict your next period start date.",
            met_weight_unit: "Weight Unit",
            met_height_unit: "Height Unit",
            met_temp_unit: "Body Temperature Unit",
            mood_name: "Moods Name",
            mood_sh: "Show/Hide",
            pass_clear: "Clear your password setup",
            symp_name: "Symptoms Name",
            symp: "Symptoms",
            mood: "Moods",
            preg_congrat: "Congratulations! Click continue to turn on your pregnancy mode.",
            preg_mistake: "If you've turned pregnancy mode on by mistake, you can turn it off here.",
            preg_option1: "XXX DAYS TO BABY",
            preg_option2: "X Week X Day since pregnancy",
            preg_choose: "Please choose one option to show on the homepage",
            preg_est: "Estimated start of gestation",
            preg_est_due: "Estimated due date",
            preg_display:"Display on the homepage",
            preg_misc: "Delivery or miscarriage",
            preg_im_no: "I'm no longer pregnant",
            preg_my_mis: "Turn on my mistake",
            preg_turn_off: "Turn off pregnancy mode",
            preg_tap_i: "Tapping I'm pregnant will pause the period cycle, and start the coutdown to your delivery day.",
            preg_im: "I'm pregnant"
        },
        sp:{
            tab_calendar: "Calendario",
            tab_log: "la log",
            tab_chart: "Gráfico",
            tab_setting: "Ajuste",
            tab_note: "Añadir la nota",
            period_text1: "st DIAS DE PERIODO",
            period_text2: "nd DIAS DE PERIODO",
            period_text3: "rd DIAS DE PERIODO",
            period_text4: "th DIAS DE PERIODO",
            cycle_text: "Días restantes",
            next_period: "Siguiente periodo",
            next_text: "Siguiente fértil",
            sub_theme: "Tema",
            sub_theme_text: "Puede cambiar el estilo y el color del tema",
            sub_symptomood: "Síntomas y estados de ánimo",
            sub_symptomood_text: "Puedes actualizar los cambios de humor",
            sub_lang: "Opciones de lenguaje",
            sub_lang_text: "Puedes cambiar el idioma",
            sub_metric: "Unidades métricas e imperiales",
            sub_metric_text: "Puedes cambiar los detalles de tu unidad",
            sub_reminder: "Recordatorio",
            sub_reminder_text: "Recordatorio de período, ovulación y medicamentos",
            sub_pass: "Contraseña",
            sub_pass_text: "Asegure la autenticación de su aplicación",
            sub_backup: "Copia de seguridad de restauracion",
            sub_backup_text: "Asegure sus datos y recupere en cualquier momento",
            dash_daysbaby: " Días al bebé",
            dash_preg:" desde el embarazo",
            dash_title_details: "Introduce tus detalles",
            dash_length_of:"La longitud de tu",
            dash_period_t:"Período",
            dash_bleed_bet: "El sangrado suele durar entre 4 y 7 días.",
            dash_cannot_empty: "Este campo no puede estar vacío",
            dash_length_mens: "¿La duración de su ciclo menstrual?",
            dash_duration_of:"La duración de la fecha de inicio de dos períodos, generalmente de 23 a 35 días.",
            dash_start_period: "¿La fecha de inicio de su último período?",
            dash_date_valid: "Seleccione la fecha primero",
            dash_btn_cancel: "Cancelar",
            dash_btn_done: "Hecho",
            dash_select_lang: "elige tu idioma",
            dash_welcome: "Bienvenida",
            dash_new_user: "Nueva usuaria",
            dash_used_before: "He usado antes",
            dash_restore: "Restaurar datos",
            note_add_text: "Añadir la nota",
            note_add_btn: "Añadir",
            note_condom: "Opción de condón",
            note_unprotect: "Desprotegida",
            note_protect: "Protegida",
            note_orgasm: "Orgasmo femenino",
            note_yes: "Yes",
            note_no: "No",
            note_how_many: "Cuantas veces",
            note_weight: "Peso",
            note_height: "Altura",
            note_temp: "Temperatura",
            note_target: "Objetivo",
            note_p_start: "Inicio de período",
            note_flow: "Fluir",
            note_p_end: "Finaliza el período",
            note_text: "Nota",
            note_interc: "Coito",
            note_water: "Beber agua",
            user_add: "Agregar una cuenta nueva",
            user_cancel: "CANCELAR",
            user_add_text: "AÑADIR",
            user_edit: "Editar",
            user_update_btn: "ACTUALIZAR",
            user_delete: "Eliminar",
            user_tap: "Toque para cambiar, lomg presione para editar o eliminar",
            back_sync: "Sincronizar datos",
            back_last_sync: "Hora de la última sincronización ",
            back_signin: "Inicie sesión y sincronice sus datos",
            back_lost_msg: "Para que sus datos no se pierdan cuando cambie su dispositivo.",
            back_signout: "Desconectar",
            bar_today: "Hoy",
            bar_ovul: "Ovulación",
            bar_add_p: "Agregar período",
            bar_past: "Pasada",
            bar_pred: "Predicción",
            fertile_start: "comienzo",
            fertile_end: "Fin",
            ovu_luteal: "Duración de la fase lútea",
            ovu_days: "Dias",
            ovu_we_use: "Usamos esta duración de la fase lútea para predecir su próxima ovulación",
            ovu_update:"Actualizar",
            set_period: "PERÍODO",
            set_period_l: "Duración del período",
            set_cycle_l: "Duración del ciclo",
            set_ovu: "Ovulación y Fértil",
            set_preg: "El embarazo",
            set_remind_head: "RECORDATORIOS",
            set_remind: "Recordatorios",
            set_remind_text: "Periodo, ovulación y medicina",
            set_person: "PERSONALIZAR",
            set_theme: "Tema",
            set_cal: "Calendario",
            set_data: "DATOS Y CUENTA",
            set_add_another: "Agregar otra usuaria",
            set_gen: "AJUSTES GENERALES",
            set_other: "OTRAS",
            set_delete: "Borrar todos los datos",
            cycle_predict: "Usamos la duración de este ciclo para predecir la fecha de inicio del próximo período.",
            met_weight_unit: "Unidad de peso",
            met_height_unit: "Unidad de altura",
            met_temp_unit: "Unidad de temperatura corporal",
            mood_name: "Moods Name",
            mood_sh: "Show/Hide",
            pass_clear: "Borrar la configuración de su contraseña",
            symp_name: "Symptoms Name",
            symp: "Síntomas",
            mood: "Estados de ánimo",
            preg_congrat: "¡Felicidades! Haga clic en continuar para activar su modo de embarazo.",
            preg_mistake: "Si activó el modo de embarazo por error, puede desactivarlo aquí.",
            preg_option1: "XXX DAYS TO BABY",
            preg_option2: "X Week X Day since pregnancy",
            preg_choose: "Elija una opción para mostrar en la página de inicio",
            preg_est: "Inicio estimado de la gestación",
            preg_est_due: "Fecha de vencimiento estimada",
            preg_display:"Mostrar en la página de inicio",
            preg_misc: "Parto o aborto espontáneo",
            preg_im_no: "Ya no estoy embarazada",
            preg_my_mis: "Enciende mi error",
            preg_turn_off: "Desactiva el modo de embarazo",
            preg_tap_i: "Al tocar Estoy embarazada pausará el ciclo del período y comenzará la bajada hasta el día del parto.",
            preg_im: "estoy embarazada"
            
        }
    }
}